# Generated by Django 3.1.6 on 2021-02-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('discription', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
