# Generated by Django 3.1.6 on 2021-02-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210206_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_date',
            field=models.IntegerField(),
        ),
    ]
