# Generated by Django 3.1.6 on 2021-02-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210207_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adress',
            field=models.CharField(default='bhagawati tole palpa', max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
