# Generated by Django 3.1.6 on 2021-04-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
